[package]
name = "libbdgt"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/GeorgyFirsov/libbdgt"
homepage = "https://github.com/GeorgyFirsov/libbdgt"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
gpgme = "0.11.0"
dirs = "5.0.1"
uuid = { version = "1.4.1", features = ["v4"] }
rusqlite = { version = "0.29.0", features = ["chrono"] }
