[package]
name = "libbdgt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpgme = "0.11.0"
chrono = "0.4.26"
dirs = "5.0.1"
rusqlite = { version = "0.29.0", features = ["chrono"] }
